server:
  port: 8081
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    platform: org.hibernate.dialect.H2Dialect
  jpa:
    show-sql: true
